name: Mirror from Org Repo

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 03:00 UTC
  workflow_dispatch:      # Allow manual run from Actions tab

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror Org to Personal
        env:
          SOURCE_REPO: https://github.com/HDA1472/HDAnalyzeR.git
          TARGET_REPO: https://x-access-token:${{ secrets.GH_PAT }}@github.com/kantonopoulos/HDAnalyzeR.git
        run: |
          git clone --mirror $SOURCE_REPO
          cd HDAnalyzeR.git
          git remote set-url origin $TARGET_REPO
          git push --mirror
